<a href="https://colab.research.google.com/github/rudrakshagrawal60-netizen/Pandas_Load_Transform/blob/main/Pandas_Load_Transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data Structure
# Handle Missing Values
# Data Transformation
# String Manipulation

In [ ]:
import pandas as pd
import numpy as np

# Create your clean and correct dataset
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Rahul Kumar', 'Amit Sharma', 'Priya Singh', 'Neha Verma', 'Ravi Kumar', 'Anjali Gupta', 'Vikas Singh', 'Pooja Sharma', 'Karan Mehta', 'Sneha Kumari'],
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Department': ['CSE', 'CSE', 'ECE', 'CSE', 'ME', 'CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Age': [20, 21, np.nan, 22, 23, 20, np.nan, 21, 22, 23],
    'Attendance': [85, 72, 90, np.nan, 75, 88, 92, np.nan, 76, 64],
    'Marks': [85, 72, np.nan, 91, 68, 88, 55, np.nan, 76, 64],
    'Email': ['rahul@gmail.com', 'amit@gmail.com', 'priya@gmail.com', 'neha@gmail.com', 'None', 'anjali@gmail.com', 'vikas@gmail.com', 'pooja@gmail.com', 'karan@gmail.com', 'sneha@gmail.com']
}

# Convert dictionary to Pandas DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
display(df)

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
0,101,Rahul Kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,Amit Sharma,Male,CSE,21.0,72.0,72.0,amit@gmail.com
2,103,Priya Singh,Female,ECE,NaN,90.0,NaN,priya@gmail.com
3,104,Neha Verma,Female,CSE,22.0,NaN,91.0,neha@gmail.com
4,105,Ravi Kumar,Male,ME,23.0,75.0,68.0,None
5,106,Anjali Gupta,Female,CSE,20.0,88.0,88.0,anjali@gmail.com
6,107,Vikas Singh,Male,ECE,NaN,92.0,55.0,vikas@gmail.com
7,108,Pooja Sharma,Female,CSE,21.0,NaN,NaN,pooja@gmail.com
8,109,Karan Mehta,Male,ME,22.0,76.0,76.0,karan@gmail.com
9,110,Sneha Kumari,Female,ECE,23.0,64.0,64.0,sneha@gmail.com

In [13]:
print('Shape:',df.shape)
print('Columns:',df.columns.tolist)
print('Data Types:',df.dtypes)
display(df.head())
display(df.tail())

Shape: (10, 8)
Columns: <bound method IndexOpsMixin.tolist of Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Marks', 'Email'],
      dtype='object')>
Data Types: Student_ID      int64
Name           object
Gender         object
Department     object
Age           float64
Attendance    float64
Marks         float64
Email          object
dtype: object

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
0,101,Rahul Kumar,Male,CSE,20.0,85.0,85.0,rahul@gmail.com
1,102,Amit Sharma,Male,CSE,21.0,72.0,72.0,amit@gmail.com
2,103,Priya Singh,Female,ECE,NaN,90.0,NaN,priya@gmail.com
3,104,Neha Verma,Female,CSE,22.0,NaN,91.0,neha@gmail.com
4,105,Ravi Kumar,Male,ME,23.0,75.0,68.0,None

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email
5,106,Anjali Gupta,Female,CSE,20.0,88.0,88.0,anjali@gmail.com
6,107,Vikas Singh,Male,ECE,NaN,92.0,55.0,vikas@gmail.com
7,108,Pooja Sharma,Female,CSE,21.0,NaN,NaN,pooja@gmail.com
8,109,Karan Mehta,Male,ME,22.0,76.0,76.0,karan@gmail.com
9,110,Sneha Kumari,Female,ECE,23.0,64.0,64.0,sneha@gmail.com

In [14]:
# Detect Missing values
print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           2
Attendance    2
Marks         2
Email         0
dtype: int64

In [17]:
# Handle the missing values
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].median())
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Email'] = df['Email'].fillna('Not Provided')

print(df.isnull().sum())

Student_ID    0
Name          0
Gender        0
Department    0
Age           0
Attendance    0
Marks         0
Email         0
Attenance     0
dtype: int64

In [18]:
# Data Transformation
df['Result'] = df['Marks'].apply(lambda x: 'Pass' if x >= 75 else 'Fail')

def assign_grade(marks):
    if marks >= 80:
        return 'A'
    elif marks >= 60:
        return 'B'
    elif marks >= 40:
        return 'C'
    elif marks >= 35:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Marks'].apply(assign_grade)
display(df)

,Student_ID,Name,Gender,Department,Age,Attendance,Marks,Email,Attenance,Result,Grade
0,101,Rahul Kumar,Male,CSE,20.0,85.0,85.000,rahul@gmail.com,85.0,Pass,A
1,102,Amit Sharma,Male,CSE,21.0,72.0,72.000,amit@gmail.com,72.0,Fail,B
2,103,Priya Singh,Female,ECE,21.5,90.0,74.875,priya@gmail.com,90.0,Fail,B
3,104,Neha Verma,Female,CSE,22.0,80.5,91.000,neha@gmail.com,80.5,Pass,A
4,105,Ravi Kumar,Male,ME,23.0,75.0,68.000,None,75.0,Fail,B
5,106,Anjali Gupta,Female,CSE,20.0,88.0,88.000,anjali@gmail.com,88.0,Pass,A
6,107,Vikas Singh,Male,ECE,21.5,92.0,55.000,vikas@gmail.com,92.0,Fail,C
7,108,Pooja Sharma,Female,CSE,21.0,80.5,74.875,pooja@gmail.com,80.5,Fail,B
8,109,Karan Mehta,Male,ME,22.0,76.0,76.000,karan@gmail.com,76.0,Pass,B
9,110,Sneha Kumari,Female,ECE,23.0,64.0,64.000,sneha@gmail.com,64.0,Fail,B